general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 4 min: reduz brilho para 10%
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 5 min: bloqueia a tela
listener {
    timeout = 300
    on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch dpms on
}

# 8 min: desliga o display
listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 15 min: suspende o sistema
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
